// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARvbS6oMEuBJH8sSVX97zrMzsNrBgT0vY',
    appId: '1:1072224863257:web:b908fd6001ef6bbe831688',
    messagingSenderId: '1072224863257',
    projectId: 'ahgzly-80c51',
    authDomain: 'ahgzly-80c51.firebaseapp.com',
    storageBucket: 'ahgzly-80c51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC44K-o1uQ5EE1TKndGoS1RYRhvNU5zfjs',
    appId: '1:1072224863257:android:6cd352010c9d887d831688',
    messagingSenderId: '1072224863257',
    projectId: 'ahgzly-80c51',
    storageBucket: 'ahgzly-80c51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_wHWcl8uN2l7ZvqU7TAVtvip9yXsCBoY',
    appId: '1:1072224863257:ios:5d56793d9fba782b831688',
    messagingSenderId: '1072224863257',
    projectId: 'ahgzly-80c51',
    storageBucket: 'ahgzly-80c51.appspot.com',
    iosBundleId: 'com.example.ahgzly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_wHWcl8uN2l7ZvqU7TAVtvip9yXsCBoY',
    appId: '1:1072224863257:ios:c1d43737f8182120831688',
    messagingSenderId: '1072224863257',
    projectId: 'ahgzly-80c51',
    storageBucket: 'ahgzly-80c51.appspot.com',
    iosBundleId: 'com.example.ahgzly.RunnerTests',
  );
}
